//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVBot.DataObjects.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PVBot.DataObjects.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pvbot.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a emoji in the message..
        /// </summary>
        public static string ChatScreenEmojiButtonDescription {
            get {
                return ResourceManager.GetString("ChatScreenEmojiButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a file message..
        /// </summary>
        public static string ChatScreenFileButtonDescription {
            get {
                return ResourceManager.GetString("ChatScreenFileButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pvbot is thinking....
        /// </summary>
        public static string ChatScreenLoadingMessage {
            get {
                return ResourceManager.GetString("ChatScreenLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the options..
        /// </summary>
        public static string ChatScreenOptionsButtonDescription {
            get {
                return ResourceManager.GetString("ChatScreenOptionsButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends the message..
        /// </summary>
        public static string ChatScreenSendButtonDescription {
            get {
                return ResourceManager.GetString("ChatScreenSendButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingScreenMessage {
            get {
                return ResourceManager.GetString("LoadingScreenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pvbot logo..
        /// </summary>
        public static string MainScreeLogoDescription {
            get {
                return ResourceManager.GetString("MainScreeLogoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, please!.
        /// </summary>
        public static string MainScreenCustomerAnswer {
            get {
                return ResourceManager.GetString("MainScreenCustomerAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi!, I&apos;m.
        /// </summary>
        public static string MainScreenGreetings {
            get {
                return ResourceManager.GetString("MainScreenGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there something I can help you?.
        /// </summary>
        public static string MainScreenQuestion {
            get {
                return ResourceManager.GetString("MainScreenQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know what to say, just yet!.
        /// </summary>
        public static string PvbotDefaultResponse {
            get {
                return ResourceManager.GetString("PvbotDefaultResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a WIP!.
        /// </summary>
        public static string WipDialogMessage {
            get {
                return ResourceManager.GetString("WipDialogMessage", resourceCulture);
            }
        }
    }
}
